---
  - name: "Create zookeeper directory"
    hosts: zookeeper
    file:
      path: "{{item}}"
      owner: root
      mode: 0755
      state: directory
    with_items: 
    - '/etc/kafka'
    - '/var/lib/zookeeper'
    tags: zookeeper_config

  - name: "create id file"
    hosts: zookeeper
    file:
      path: /var/lib/zookeeper/myid
      owner: root
      state: present
    tags: zookeeper_config

  - name: "Zookeeper configuration"
    hosts: zookeeper
    template:
     src:  "{{item.src}}"
     dest: "{{item.dest}}"
     owner: root
     group: root
     mode: 0655
    with_items:
    - { src: 'zookeeper.properties.j2',dest: '/etc/kafka/zookeeper.properties'}
    - { src: 'myid.j2' ,dest: '/var/lib/zookeeper/myid'}
    tags: zookeeper_config


  


   


